name: Validate Pull Request

on:
  pull_request:

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Validate Pull Request
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Validate Pull Request Message
      run: |
        cat << 'EOM' | npx commitlint --verbose --config commitlint.config.js
        ${{ github.event.pull_request.title }}

        ${{ github.event.pull_request.body }}
        EOM

    - name: Validate Commit Messages
      run: |
        npx commitlint \
        --from ${{ github.event.pull_request.base.sha }} \
        --to ${{ github.event.pull_request.head.sha }} \
        --verbose \

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - validate-pull-request
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Fetch Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patches
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
