name: Validate Pull Request

on:
  pull_request:

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Validate Pull Request
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0

    - name: Setup node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Pull request linter action
      uses: JulienKode/pull-request-name-linter-action@v0.4.0

    - name: Commit Linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: wagoid/commitlint-github-action@v4.1.9

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build
